### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jamesjmeyer210** [MeyerMoore/BootstrapGridSystem#1]
- [x] make todo issue
- [x] css color variables
- [x] font
- [x] test media queries

**Comment by rob-moore1894** [comment]
- [x] heading for "codeup design"
- [x] tab links underneath

**Comment by jamesjmeyer210** [comment]
### For the mobile version
- [x] add nav bar in html
- [x] add title "codeup design"
- [x] add links below title "services -- work -- blog -- contact"
- [x] add header "VISUAL DESIGN & WEB DEVELOPMENT"
- [x] add sub-header "FROM PARK CITY, UTAH"
- [x] add 4 circular buttons
- [x] add "select work" text
- [x] add image
- [x] add "featured product" and round buttons

**Comment by rob-moore1894** [comment]
- [x] fix logo with Dorian's logo
- [x] put background color

**Comment by jamesjmeyer210** [comment]
### Extra Small Screens
- [x] fix button sizes for extra small screen sizes
    - [x] large buttons to fit 2 x 2
    - [x] small buttons are constant size through entire doc | make new class for them
- [x] make logo resize
- [x] resize the featured product images to fit the small screen

**Comment by jamesjmeyer210** [comment]
- [ ] We should probably put all the buttons inside forms or at least anchor tags.
- [ ] Add text/links to navbar for non-xs screens
- [x] Add hr for all non-xs screens
- [ ] Add borders to pictures

## Global
- [x] Make h6 global

## XS Screen
- [x] Add custom nav class to css and html

## SM Screen
- [x] Add custom nav class to css and html
- [x] Place round buttons in an inline list and make invisible to XS
- [ ] Make images into a 2 x 2 grid and hide on xs

## MD Screen
- [x] Add custom nav class to css and html
- [ ] Add right column for medium screen
    - [ ] Three adds in right column
    - [ ] Some twitter feed in right colum

## LG Screen
- [x] Add custom nav class to css and html
- [ ] LG screen's container should resize to accommodate the md right column
